version: "3.9"

services:
  postgres:
    container_name: flashcards-postgres
    image: "postgres:15.1"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashcards
